### ISSUE TITLE
Not able to retrieve files 25MB or more

### ISSUE THREAD

**Issue by johnnyq** [cupcakearmy/cryptgeon#80]
We are using the docker compose with Traefik example you have with a File Limit set to 500 MiB. We can upload a 25MB or greater file we just cannot retrieve the 25MB or larger file

When retrieving the file and clicking on view note we get this message

**wrong password. could not decipher. probably a broken link. note was destroyed.**

Anything below 25MB we can retrieve with no problem

Is there another limit somewhere we are missing?

**Comment by cupcakearmy** [comment]
Could you share the config?

**Comment by angelfor3v3r** [comment]
> Could you share the config?

I'm getting the same issue.

I've uploaded a 27MB file and I get a `wrong password. could not decipher. probably a broken link. note was destroyed.` when I try to download it from the note. Smaller sizes seem to work fine, I'm going to guess it's around the 25 MiB mark.

Could it perhaps be a browser/Traefik configuration issue as well? Just throwing out ideas.

I also noticed that even though I have `SIZE_LIMIT: 50 MiB` set in my Docker Compose config, the site renders the max size incorrectly as `max: 37 MiB`. Could this also be related somehow? It seems to happen with any size I set and displays an incorrect size.

Anyway. Here's my configuration and I'm running Traefik in front of it.
```yaml
cryptgeon-redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: cryptgeon-redis
    networks: [internal]
    volumes:
        - /docker/site/cryptgeon/redis:/data
    command: redis-server --maxmemory 8gb --maxmemory-policy allkeys-lru
cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    restart: unless-stopped
    container_name: cryptgeon
    networks: [internal, public]
    environment:
        REDIS: redis://cryptgeon-redis/
        SIZE_LIMIT: 50 MiB
        MAX_VIEWS: 100
        MAX_EXPIRATION: 1440
        ALLOW_ADVANCED: true
        ID_LENGTH: 32
        VERBOSITY: warn
```

I apologize if I've configured something incorrectly, I just set this up tonight on my host. I will say, it was really easy to set up. The only other complaint I have is the documentation for setting up Traefik seems to be very scattered and inconsistent. The Github repo and Docker hub pages seem to give different instructions, but thats unrelated to this issue.

**Comment by microbearlogist** [comment]
Same issue here (same parameters, I even bring the size limit up to 500MiB without any change):
I gave a look on debug bug it do not help.

With a file <=25Mb:

```
[2024-05-29T16:30:47Z INFO  actix_web::middleware::logger] "GET /api/live/ HTTP/1.1" 200 0 0.000654
[2024-05-29T16:31:15Z INFO  actix_web::middleware::logger] "GET /api/status/ HTTP/1.1" 200 222 0.000486
[2024-05-29T16:31:27Z INFO  actix_web::middleware::logger] "POST /api/notes/ HTTP/1.1" 200 73 0.357761
[2024-05-29T16:31:32Z DEBUG actix_files::service] error handling /note/5r7U7R5t5J5y7V6v6E4X4J4i6A5o8F6g7q7s5e8B5B775i7j4U7S554x6V6x7m4G: No such file or directory (os error 2)
[2024-05-29T16:31:32Z INFO  actix_web::middleware::logger] "GET /note/5r7U7R5t5J5y7V6v6E4X4J4i6A5o8F6g7q7s5e8B5B775i7j4U7S554x6V6x7m4G HTTP/1.1" 200 1106 0.000720
[2024-05-29T16:31:32Z INFO  actix_web::middleware::logger] "GET /api/status/ HTTP/1.1" 200 222 0.000437
[2024-05-29T16:31:32Z INFO  actix_web::middleware::logger] "GET /api/notes/5r7U7R5t5J5y7V6v6E4X4J4i6A5o8F6g7q7s5e8B5B775i7j4U7S554x6V6x7m4G HTTP/1.1" 200 30 0.233054
[2024-05-29T16:31:34Z INFO  actix_web::middleware::logger] "DELETE /api/notes/5r7U7R5t5J5y7V6v6E4X4J4i6A5o8F6g7q7s5e8B5B775i7j4U7S554x6V6x7m4G HTTP/1.1" 200 33404025 0.645869
```


With a bigger file:
```
[2024-05-29T16:32:21Z INFO  actix_web::middleware::logger] "GET / HTTP/1.1" 304 0 0.000198
[2024-05-29T16:32:21Z INFO  actix_web::middleware::logger] "GET /api/status/ HTTP/1.1" 200 222 0.000557
[2024-05-29T16:32:48Z INFO  actix_web::middleware::logger] "GET /api/live/ HTTP/1.1" 200 0 0.001011
[2024-05-29T16:32:58Z INFO  actix_web::middleware::logger] "POST /api/notes/ HTTP/1.1" 200 73 3.176419
[2024-05-29T16:33:02Z DEBUG actix_files::service] error handling /note/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l: No such file or directory (os error 2)
[2024-05-29T16:33:02Z INFO  actix_web::middleware::logger] "GET /note/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l HTTP/1.1" 200 1106 0.001374
[2024-05-29T16:33:02Z DEBUG actix_files::service] error handling /favicon.ico: No such file or directory (os error 2)
[2024-05-29T16:33:02Z INFO  actix_web::middleware::logger] "GET /favicon.ico HTTP/1.1" 200 1106 0.001029
[2024-05-29T16:33:02Z INFO  actix_web::middleware::logger] "GET /api/status/ HTTP/1.1" 200 222 0.000592
[2024-05-29T16:33:04Z INFO  actix_web::middleware::logger] "GET /api/notes/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l HTTP/1.1" 200 30 2.126938
[2024-05-29T16:33:11Z INFO  actix_web::middleware::logger] "DELETE /api/notes/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l HTTP/1.1" 200 360705253 6.885257
[2024-05-29T16:33:20Z INFO  actix_web::middleware::logger] "DELETE /api/notes/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l HTTP/1.1" 404 0 0.001082
[2024-05-29T16:33:21Z INFO  actix_web::middleware::logger] "DELETE /api/notes/7B7N6t7K7N4T866w7M7E7V4c4J6b4j7j4c72814W4F795L796y5m7f5Y6U4p4v6l HTTP/1.1" 404 0 0.001057@
```

My web server has no file size limit and my browser shows no errors. It seems to be on Cryptgeon's side.
Do you any any clues @cupcakearmy ?
How can I provide you with more information than this debug?

**Comment by EasedVR** [comment]
Unfortunately I also have this issue. The only thing I can add for now is that it seems to be browser related. With Firefox (on Android and Windows) I get the same error message when trying to open the message. With Chrome on Windows I don't have this problem.
I deploy using portainer with this config:

`
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 256 MiB
    ports:
      - 86:8000
    restart: unless-stopped`

**Comment by microbearlogist** [comment]
I can confirm that it works without a hitch with Chrome.

Seeing no error with Firefox, I hadn't thought of testing another browser. Thanks for the information @EasedVR !

I've done some testing and it's actually the decryption step that doesn't work under Firefox for files over 25MB (a file uploaded from Firefox opens without a problem under Chrome). The upload stage is therefore out of the problem.


I still cannot find any error message whether on the server or browser side so I'm stuck :/

**Comment by cupcakearmy** [comment]
I'm currently rewriting the backend with axum, and i had some issues before with flaky tests regarding the max upload and stuff. I'd assume it will be finally fixed with axum. Will add a test with bigger files to validate :)

**Comment by cupcakearmy** [comment]
Can confirm in Safari and Firefox can upload, but not download, for some reason.

**Comment by cupcakearmy** [comment]
Could not replicate anymore in safari, will close for now. Feel free to reopen :)

**Comment by EasedVR** [comment]
Nothing changed on my side unfortunately. Still the same error with Firefox. No problem with Chrome with the same file.

![Image](https://github.com/user-attachments/assets/d5d5b101-22b4-4c3e-88ac-76915af3c1ac)
